WITH X AS(
    SELECT CAR_ID,CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단','SUV')
),
 Y AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' 
          AND END_DATE >= '2022-11-01'
)

SELECT X.CAR_ID, Z.CAR_TYPE, FLOOR((X.DAILY_FEE * ((100 - Z.DISCOUNT_RATE) / 100) * 30)) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN Z INNER JOIN X USING(CAR_TYPE)
WHERE Z.DURATION_TYPE = '30일 이상'
AND (X.DAILY_FEE * ((100 - Z.DISCOUNT_RATE) / 100) * 30)  >= 500000
AND (X.DAILY_FEE * ((100 - Z.DISCOUNT_RATE) / 100) * 30) < 2000000
AND X.CAR_ID NOT IN (SELECT CAR_ID FROM Y)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC