SELECT s.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO s 
join (
    SELECT FOOD_TYPE, MAX(FAVORITES) as max_fav
    FROM REST_INFO
    GROUP BY FOOD_TYPE
     ) r
ON s.FOOD_TYPE = r.FOOD_TYPE and s.FAVORITES = r.max_fav
ORDER BY FOOD_TYPE desc