WITH T AS(
    SELECT USER_ID 
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT 
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID) / (
    SELECT COUNT(*)
    FROM T
),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM T
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC