-- 코드를 입력하세요
SELECT P1.CATEGORY,  P2.MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P1 JOIN (
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')
GROUP BY CATEGORY 
) P2
ON P1.CATEGORY = P2.CATEGORY
WHERE P1.PRICE = P2.MAX_PRICE
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC